# written by OuOhaha
from pydub import AudioSegment
import pandas as pd

### CHANGE YOUR FILE NAME HERE ###

FILE_NAME = "example"
AUDIO_FORMAT = "mp3"

### CHANGE YOUR FILE NAME HERE ###

# Load the audio
file = FILE_NAME + "." + AUDIO_FORMAT
if AUDIO_FORMAT == "mp3":
    audio = AudioSegment.from_mp3(file)
elif AUDIO_FORMAT == "wav":
    audio = AudioSegment.from_wav(file)
else:
    audio = AudioSegment.from_file(file)

# Load the tsv file generated by whisper
stamps = FILE_NAME + ".tsv"
stamp_list = pd.read_csv(stamps, sep='\t', header=0).iloc[:, :2].apply(lambda row: f"({row[0]}, {row[1]})", axis=1).to_list()
time_stamp = []

for item in stamp_list:
    value_tuple = eval(item)
    time_stamp.append(value_tuple)

# Split the audio and save segments
for i, (start, end) in enumerate(time_stamp, start=1):
    segment = audio[start:end]
    segment.export(f"{i}.mp3", format="mp3")
